### ISSUE TITLE
 How to run my own topology

### ISSUE THREAD

**Issue by gaovivid** [mzc796/marionette_onos#1]
Hello, if I want to run my own topology, do I only need to modify the motivating_example_topo.py file, or do I need to modify other files as well?

**Comment by mzc796** [comment]
Hi, for the request to run your own topology, you will only need to modify the motivating_example_topo.py. However, if you want to manipulate links precisely based on your topology, you will need to understand how the links can be manipulated precisely and modify topo_poison.sh file accordingly.  You may need to read Section 5 and Appendix A in the paper (https://doi.org/10.48550/arXiv.2408.16940). Otherwise, the topology may change but it probably won't be a precise link manipulation unless you have the motivating example topology as a part of your topology with switch IDs matched.

This repository provides a simplified example to demonstrate the effectiveness of the attack on ONOS cluster. The complete marionette attack is on the repository of marionette_odl(https://github.com/mzc796/marionette_odl) which includes computing a good deceptive topology by Reinforcement Learning (RL) given attack goals with expected similarity, and automatically generating poisonous flow entries to realize this deceptive topology (i.e. letting the legitimate controller discover this deceptive topology independently). For marionette_odl, you may need to adjust RL model parameters if you want to attack your self-defined topology. Please let me know if you need further help. Thanks!

**Comment by gaovivid** [comment]
Thank you for your reply.

**Comment by gaovivid** [comment]
Hello, I followed the steps in "Build and Run an ONOS Cluster with Mininet," but encountered a problem during step 7. How should I resolve this issue? The images for steps 6 and 7 are attached.
![D7ED75E0B4139C339753B3E500921052](https://github.com/user-attachments/assets/e42b5dde-2043-47fe-93e2-aa2268a36f0a)


![C68963AE7B1F9840917D4F39BCC14A49](https://github.com/user-attachments/assets/47d15a9f-a68e-4e6a-82eb-bb0ae06b51e6)
![75B35F46D343EDCE03BDDCDE6609B772](https://github.com/user-attachments/assets/3b17a0a3-8ec8-4812-96a0-bc2e69a04dcc)

**Comment by mzc796** [comment]
Hi, I assume you shouldn't include a comma in the URL. The URL is "http://172.17.0.5:8181/onos/ui". Also, you may need to wait for a while to let ONOS boot up. Here is the ONOS UI guidance: https://wiki.onosproject.org/display/ONOS/The+ONOS+Web+GUI

**Comment by gaovivid** [comment]
Thank you for your help. I have already solved this problem. I am currently reading the paper you shared and trying to implement my own topology.

**Comment by gaovivid** [comment]
Hello, the ONOS cluster part in the code you shared was very helpful to me, thank you very much. Could you help me with the following question?
I want to use Mininet and the ONOS controller to simulate and test the impact of deploying controllers on different devices in the topology on network performance, but I am not sure if I am doing it correctly.
In Mininet, I set up a topology, then added switches, hosts, and controllers. Each switch device is connected to a host. I set the IP addresses of several hosts to be the same as the controllers' IPs, and then I connected these hosts to the switches. Can this represent the deployment of controllers on a few switch nodes in the topology?
Below is my topology code. I set the IP addresses of h5, h6, and h7 to be exactly the same as the controllers' IP addresses, and I connected these three hosts to s5, s6, and s7. Does this simulate the deployment of controllers at these three switches, or do I need to write additional code to achieve this functionality? I hope you can help me with this question.
[topo.txt](https://github.com/user-attachments/files/16962862/topo.txt)

**Comment by mzc796** [comment]
Hi, 
First of all, no machine should have the same IP address as another in a normal case.  
You may need to understand how Mininet simulates OpenFlow networking and how to set up an SDN environment with [Mininet](https://mininet.org/walkthrough/). There are two types of controller that Mininet can connect with, (1) local controller, Mininet has a simple controller (Pox, if I remember correctly) built locally. That is the part of adding controllers in your code. If you use a local controller, you don't need to configure a controller when running the Mininet. After you run Mininet with your customized_topo.py, the controller is there (Let's say your customized_topo.py is bug-free). (2) remote controller, which means the controller can be any controller supporting OpenFlow protocol. In my case, I use two ONOS as remote controllers. you can check my script for running the Mininet. There is a configuration to connect with a remote controller by specifying IP and port number. I suggest you start with the SDN environment setup, then go back here. The poisonous flow entry configuration can be very convoluted. 

I am going to close this session because the problem/misunderstanding related to marionette_onos repository has been solved.
